/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fireice;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author giang
 */
public class ConfigForm extends javax.swing.JFrame {

    /**
     * Creates new form ConfigForm
     */
    ButtonGroup rbtn_GroupPlayFirst;
    ButtonGroup rbtn_GroupColor;
    
    final BufferedImage redBlock;
    final BufferedImage blueBlock;
    
    public ConfigForm() throws IOException {
        initComponents();
        rbtn_GroupPlayFirst =new ButtonGroup();    
        rbtn_GroupPlayFirst.add(rbtn_AIFirst);
        rbtn_GroupPlayFirst.add(rbtn_HumanFirst);   
        
        rbtn_GroupColor=new ButtonGroup();    
        rbtn_GroupColor.add(rbtn_Red);
        rbtn_GroupColor.add(rbtn_Blue);
        
        redBlock = ImageIO.read(new File("img/r64.png"));
        blueBlock = ImageIO.read(new File("img/b64.png"));
        
         File f = null;
        String[] paths;
        int count = 0;
        try {
            f = new File("boards");
            paths = f.list();
            for (String path : paths) {
                count ++;
                listMap.addItem(path);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        //lbBoard.setText("Boards (found"+count+" files)");
        
        this.rbtn_HumanFirst.setSelected(true);
        this.rbtn_Red.setSelected(true);
    }
    
    
    
    public void paint(Graphics g) {
        super.paint(g);
        
        int dx = 20, dy=120 ;
        g.drawImage(redBlock, dx, dy, null);
        
        dx = 175 ;
        dy=120 ;
        g.drawImage(blueBlock, dx, dy, null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtn_HumanFirst = new javax.swing.JRadioButton();
        rbtn_AIFirst = new javax.swing.JRadioButton();
        rbtn_Blue = new javax.swing.JRadioButton();
        rbtn_Red = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_StartGame = new javax.swing.JButton();
        lbBoard = new javax.swing.JLabel();
        listMap = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FireIce v1.0");

        rbtn_HumanFirst.setText("Human");
        rbtn_HumanFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_HumanFirstActionPerformed(evt);
            }
        });

        rbtn_AIFirst.setText("AI");
        rbtn_AIFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_AIFirstActionPerformed(evt);
            }
        });

        rbtn_Blue.setText("BLUE");
        rbtn_Blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_BlueActionPerformed(evt);
            }
        });

        rbtn_Red.setText("RED");
        rbtn_Red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_RedActionPerformed(evt);
            }
        });

        jLabel1.setText("Your Color: ");

        jLabel2.setText("First Move: ");

        btn_StartGame.setText("START GAME");
        btn_StartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StartGameActionPerformed(evt);
            }
        });

        lbBoard.setText("Board:");

        listMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(rbtn_Red))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btn_StartGame)))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBoard)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtn_Blue)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(listMap, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(rbtn_HumanFirst)
                .addGap(61, 61, 61)
                .addComponent(rbtn_AIFirst)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_HumanFirst)
                    .addComponent(rbtn_AIFirst))
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Red)
                    .addComponent(rbtn_Blue))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBoard)
                    .addComponent(listMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(btn_StartGame)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    boolean isHumanPlayFirst;
    boolean isHumanRed;
    boolean closed=false;
       
    private void btn_StartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StartGameActionPerformed
        // TODO add your handling code here:
        closed = true;
        this.dispose();
    }//GEN-LAST:event_btn_StartGameActionPerformed

    private void rbtn_HumanFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_HumanFirstActionPerformed
        // TODO add your handling code here:
        isHumanPlayFirst = true;
    }//GEN-LAST:event_rbtn_HumanFirstActionPerformed

    private void rbtn_AIFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_AIFirstActionPerformed
        // TODO add your handling code here:
        isHumanPlayFirst = false;
    }//GEN-LAST:event_rbtn_AIFirstActionPerformed

    private void rbtn_RedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_RedActionPerformed
        // TODO add your handling code here:
        isHumanRed = true;
    }//GEN-LAST:event_rbtn_RedActionPerformed

    private void rbtn_BlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_BlueActionPerformed
        // TODO add your handling code here:
        isHumanRed = false;
    }//GEN-LAST:event_rbtn_BlueActionPerformed
String selectedFile = "";
    private void listMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMapActionPerformed
        // TODO add your handling code here:
        selectedFile = listMap.getSelectedItem().toString();
        //System.out.println(selectedFile);
        
    }//GEN-LAST:event_listMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ConfigForm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ConfigForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_StartGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbBoard;
    private javax.swing.JComboBox<String> listMap;
    private javax.swing.JRadioButton rbtn_AIFirst;
    private javax.swing.JRadioButton rbtn_Blue;
    private javax.swing.JRadioButton rbtn_HumanFirst;
    private javax.swing.JRadioButton rbtn_Red;
    // End of variables declaration//GEN-END:variables
}
